name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: install deps
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run package

      - name: Hash artifacts
        uses: y-not-u/electron-builder-latest-yml-action@v1
        if: startsWith(matrix.os, 'ubuntu')
        with:
          version: ${{github.ref_name}}
          artifact: 'release/build/*.AppImage'
          yml-file: 'latest-linux.yml'
      - name: Upload artifacts (AppImage)
        uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: ubuntu-AppImage
          path: |
            release/build/*.AppImage
            latest-linux.yml

      - name: Upload artifacts (dmg)
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'macOS')
        with:
          name: mac-dmg
          path: release/build/*.dmg

      - name: Hash artifacts
        uses: y-not-u/electron-builder-latest-yml-action@v1
        if: startsWith(matrix.os, 'windows')
        with:
          version: ${{github.ref_name}}
          artifact: 'release/build/*.exe'
          yml-file: 'latest.yml'
      - name: Upload artifacts (exe)
        uses: actions/upload-artifact@v3
        if: startsWith(matrix.os, 'windows')
        with:
          name: win-exe
          path: |
            latest.yml
            release/build/*.exe
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /tmp/artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          body: New release
          files: /tmp/artifacts/**
